attach(painter)
plot(age, mn)
plot(years, mn)
plot(age, years)
pt<-group=="painter"
plot(age[pt], mn[pt], pch=16, col='blue')
points(age[!pt], mn[!pt], pch=16, col='red')
m.1<-lm(mn~years+age+smoking+drinking)
confint(m.1)
res<-m.1$residuals
shapiro.test(res)
predict(m.1, data.frame(years=20, age=50, smoking=0, drinking=0), interval='confidence')
predict(m.1, data.frame(years=0, age=50, smoking=0, drinking=0), interval='confidence')
m.0<-lm(mn~years)
anova(m.0, m.1)
anova(m.1)
summary(m.1)
cor.test(age[group=='control'], mn[group=='control'])

attach(bonessri)
lm.1<-lm(femurbmd~ssriyears+age+female)
lm.0<-lm(femurbmd~ssriyears)
anova(lm.0, lm.1)
anova(lm.0)
detach(bonessri)
